Traffic Light Detection. Detection. (#7)
## What?
Updated TLClassifier Class.
Added models with weights for detection and classification of TL Lights.
Added JSON model for TL Detection because of Keras bug with `model_load` with custom objects
```python
[INFO] [1521385727.398925]: [TL_DETECTOR] Loading TLDetector model
/usr/local/lib/python2.7/dist-packages/keras/models.py:291: UserWarning: Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.
  warnings.warn('Error in loading the saved optimizer '
```
 and Adam optimizer. Because Adam Optimizer has been added in the most recent version of Keras, had to update requirements list to remove version for Keras. This will allow to instal the most recent one. 
```python
model = load_model('./....h5')  File \"/usr/local/lib/python2.7/dist-packages/keras/models.py\", line 257, in load_model    custom_objects=custom_objects)  File \"/usr/local/lib/python2.7/dist-packages/keras/optimizers.py\", line 689, in deserialize    printable_module_name='optimizer')  File \"/usr/local/lib/python2.7/dist-packages/keras/utils/generic_utils.py\", line 141, in deserialize_keras_object    return cls.from_config(config['config'])  File \"/usr/local/lib/python2.7/dist-packages/keras/optimizers.py\", line 127, in from_config    return cls(**config)  File \"/usr/local/lib/python2.7/dist-packages/keras/optimizers.py\", line 403, in __init__    super(Adam, self).__init__(**kwargs)  File \"/usr/local/lib/python2.7/dist-packages/keras/optimizers.py\", line 63, in __init__    'passed to optimizer: ' + str(k))TypeError: Unexpected keyword argument passed to optimizer: amsgrad
```
Encountered a problem with Pillow 
```python
File "/opt/ros/kinetic/lib/python2.7/dist-packages/cv_bridge/core.py", line 248, in cv2_to_imgmsg
   img_msg.height = cvim.shape[0]
```
had to upgrade it to the version >4.3. Remove requirements version constraint for Pillow.
Updated TLDetector Class to call initialize and load Classifier.

Got another bug from keras, when loading a model and weights Predict function does not recognize one of the layers from the model.
```python
[ERROR] [1521471510.962707]: bad callback: <bound method TLDetector.image_cb of <__main__.TLDetector object at 0x7f5106fab250>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/capstone/ros/src/tl_detector/tl_detector.py", line 170, in image_cb
    light_wp, state = self.process_traffic_lights()
  File "/capstone/ros/src/tl_detector/tl_detector.py", line 334, in process_traffic_lights
    state = self.get_light_state(light)
  File "/capstone/ros/src/tl_detector/tl_detector.py", line 306, in get_light_state
    tl_image = self.detect_traffic_light(cv_image)
  File "/capstone/ros/src/tl_detector/tl_detector.py", line 278, in detect_traffic_light
    image_mask = self.detector_model.predict(resize_image[None, :, :, :], batch_size=1)[0]
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1832, in predict
    self._make_predict_function()
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1029, in _make_predict_function
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 2502, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 2445, in __init__
    with tf.control_dependencies(self.outputs):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3936, in control_dependencies
    return get_default_graph().control_dependencies(control_inputs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3665, in control_dependencies
    c = self.as_graph_element(c)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2708, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2787, in _as_graph_element_locked
    raise ValueError("Tensor %s is not an element of this graph." % obj)
ValueError: Tensor Tensor("conv2d_2_1/Sigmoid:0", shape=(?, 96, 128, 1), dtype=float32) is not an element of this graph.
```
To fix this I have to call `self.detector_model._make_predict_function()` after weights and model have been initialized and loaded. Found the solution here [link](https://github.com/keras-team/keras/issues/2397).

Before detecting TL I am doing image augmentation to resize it to the proper size for the model.

After the TL was found I pass in data into TL Classifier to detect the light color.

Function `extract_image` does all the work with predicted TL Light. It takes in an image and a predicted mask and return cropped image of the TL.

```python
Set the parameter simulated_dtection in tl_detector.launch to 0 to enable live detection and
increase tl_detection_interval_frames if classification takes more than 1 frame time.
```

## Why?
Traffic Light Detection: This can be split into 2 parts:
Part1: Detection: Detect the traffic light and its color from the /image_color. The topic /vehicle/traffic_lights contains the exact location and status of all traffic lights in simulator, so you can test your output.

[x] - works on simulator
[x] - tested locally
[x] - local env version Used Docker container with Mac OS HIgh Sierra 10.13.3

* Ignores folders
* Updates requirements.txt
* Adds models
* Adds config files
* Adds light classifier
* Adds updated tl_detector
* Adds JSON models
* Adds json model ref to config
* Updates TLClassifier
* Update TLDetector
* Assign model to load_weights()
* Renames models
* Update Configs
* Debug
* Sets versions of libraries
* Call _make_predict_function() to avoid keras bug
* Remove logging
* Adds one more None label
* Update code after rebase went wrong
* Adds more logging
* improve car reactivity